ui:
  - changed-files:
      - any-glob-to-any-file:
          - app/**/*.tsx
          - app/**/*.ts
          - app/**/*.css
          - app/components/**
          - app/docs/**

config:
  - changed-files:
      - any-glob-to-any-file:
          - "*.config.*"
          - tsconfig*.json
          - tailwind.config.*
          - postcss.config.*
          - wrangler.*

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - README.md

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - pnpm-lock.yaml
